version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    container_name: discord-clone-dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000
    networks:
      - discord-network

networks:
  discord-network:
    driver: bridge 